Repository Team-ComIT/SimTong-Android, pull requests merged in 2022-11, with the labels that each got.

#23 Merge: SIMT-35 이메일 수정 및 마이페이지 수정
  core-design-system/src/main/java/com/comit/core_design_system/util/Anim.kt
  feature/feature-mypage/build.gradle.kts
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/navigation/MyPageNavigation.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/FixBaseScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/FixEmailScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/FixPassword.kt
  navigator/src/main/java/com/comit/navigator/SimTongScreen.kt
Labels: 기능 추가

#24 refactor: SIMT-39 디자인 시스템 gray 변경
  core-design-system/src/main/java/com/comit/core_design_system/button/button.kt
  core-design-system/src/main/java/com/comit/core_design_system/button/checkbox.kt
  core-design-system/src/main/java/com/comit/core_design_system/button/radiobutton.kt
  core-design-system/src/main/java/com/comit/core_design_system/color/SimTongColor.kt
  core-design-system/src/main/java/com/comit/core_design_system/component/CarrotMarket.kt
  core-design-system/src/main/java/com/comit/core_design_system/component/NoticeBoardItem.kt
  core-design-system/src/main/java/com/comit/core_design_system/component/PlaceComponent.kt
  core-design-system/src/main/java/com/comit/core_design_system/component/TextField.kt
  core-design-system/src/main/java/com/comit/core_design_system/component/Vote.kt
  core-design-system/src/main/java/com/comit/core_design_system/component/imageUploadLayout.kt
  core-design-system/src/main/java/com/comit/core_design_system/typography/typography.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/findEmployeeNumber/FindEmployeeNumScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/CheckCertificationNumberScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpNameScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/FixWorkPlaceScreen.kt
Labels: 리펙토링

#22 Merge: SIMT-37 firebase distribution
  .gitignore
  Gemfile
  Gemfile.lock
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  buildSrc/src/main/java/BuildPlugins.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/README.md
  fastlane/report.xml
Labels: Chore
