Repository Team-ComIT/SimTong-Android, pull requests merged in 2022-12, with the labels that each got.

#27 Merge: SIMT-19 SignIn 비즈니스 로직
  app/build.gradle.kts
  build.gradle.kts
  common/src/main/java/com/comit/common/domain/scope/safeLet.kt
  common/src/main/java/com/comit/common/domain/scope/whenNotNull.kt
  core-design-system/build.gradle.kts
  data/build.gradle.kts
  data/src/main/java/com/comit/data/datasource/RemoteAuthDataSource.kt
  data/src/main/java/com/comit/data/repository/AuthRepositoryImpl.kt
  di/build.gradle.kts
  di/src/main/java/com/comit/di/RemoteDataSourceModule.kt
  di/src/main/java/com/comit/di/RepositoryModule.kt
  di/src/main/java/com/comit/di/RetrofitModule.kt
  domain/build.gradle.kts
  domain/src/main/java/com/comit/domain/repository/AuthRepository.kt
  domain/src/main/java/com/comit/domain/usecase/SignInUseCase.kt
  feature/feature-auth/build.gradle.kts
  feature/feature-auth/src/main/java/com/comit/feature_auth/mvi/SIgnUpContract.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/mvi/SignInContract.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/mvi/signup/SignUpSideEffect.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signIn/SignInViewModel.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpNameScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpNicknameScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpPasswordScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpVerifyScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/vm/SignUpViewModel.kt
  feature/feature-home/build.gradle.kts
  feature/feature-mypage/build.gradle.kts
  local/build.gradle.kts
  model/.gitignore
  model/build.gradle.kts
  model/src/main/java/com/comit/model/Token.kt
  remote/build.gradle.kts
  remote/src/main/java/com/comit/remote/api/AuthAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteAuthDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/mapper/ResponseToModel.kt
  remote/src/main/java/com/comit/remote/request/users/SignInRequest.kt
  settings.gradle.kts
Labels: 기능 추가

#28 Merge: SIMT-41 AuthAPI
  data/src/main/java/com/comit/data/datasource/RemoteAuthDataSource.kt
  data/src/main/java/com/comit/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/comit/domain/repository/AuthRepository.kt
  domain/src/main/java/com/comit/domain/usecase/ChangeEmailUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/ChangeNicknameUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/ChangeProfileImageUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/ChangeSpotUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/CheckNicknameDuplicationUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/FetchUserInformationUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/SignUpUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/VerificationEmployeeUseCase.kt
  model/src/main/java/com/comit/model/User.kt
  remote/src/main/java/com/comit/remote/api/AuthAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteAuthDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/mapper/ResponseToModel.kt
  remote/src/main/java/com/comit/remote/request/users/ChangeProfileImageRequest.kt
  remote/src/main/java/com/comit/remote/request/users/ChangeSpotRequest.kt
  remote/src/main/java/com/comit/remote/response/users/FetchUserInformationResponse.kt
Labels: 기능 추가

#31 Merge: SIMT-44 Email API
  data/src/main/java/com/comit/data/datasource/RemoteEmailDataSource.kt
  data/src/main/java/com/comit/data/repository/EmailRepositoryImpl.kt
  di/src/main/java/com/comit/di/RemoteDataSourceModule.kt
  di/src/main/java/com/comit/di/RepositoryModule.kt
  domain/src/main/java/com/comit/domain/repository/EmailRepository.kt
  domain/src/main/java/com/comit/domain/usecase/email/CheckEmailCodeUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/email/SendEmailCodeUseCase.kt
  remote/src/main/java/com/comit/remote/api/EmailAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteEmailDataSourceImpl.kt
Labels: 기능 추가

#33 Merge: SIMT-46 Schedule API
  data/src/main/java/com/comit/data/datasource/RemoteScheduleDataSource.kt
  data/src/main/java/com/comit/data/repository/ScheduleRepositoryImpl.kt
  di/src/main/java/com/comit/di/RemoteDataSourceModule.kt
  di/src/main/java/com/comit/di/RepositoryModule.kt
  domain/src/main/java/com/comit/domain/repository/ScheduleRepository.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/AddPersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/ChangePersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/DeletePersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/FetchPersonalScheduleUseCase.kt
  model/src/main/java/com/comit/model/ScheduleList.kt
  remote/src/main/java/com/comit/remote/api/ScheduleAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteScheduleDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/mapper/ResponseToModel.kt
  remote/src/main/java/com/comit/remote/request/schedules/AddPersonalScheduleRequest.kt
  remote/src/main/java/com/comit/remote/request/schedules/AdditionAllSchedulesRequest.kt
  remote/src/main/java/com/comit/remote/request/schedules/AdditionSchedulesRequest.kt
  remote/src/main/java/com/comit/remote/request/schedules/ChangePersonalScheduleRequest.kt
  remote/src/main/java/com/comit/remote/request/schedules/ChangeSchedulesRequest.kt
  remote/src/main/java/com/comit/remote/request/schedules/DeleteSchedulesRequest.kt
  remote/src/main/java/com/comit/remote/request/schedules/SchedulesRequest.kt
  remote/src/main/java/com/comit/remote/request/schedules/SimpleSchedulesRequest.kt
  remote/src/main/java/com/comit/remote/response/schedules/FetchPersonalScheduleResponse.kt
  remote/src/main/java/com/comit/remote/response/schedules/SchedulesResponse.kt
Labels: 기능 추가

#30 Merge: SIMT-43 Files API
  data/src/main/java/com/comit/data/datasource/RemoteFileDataSource.kt
  data/src/main/java/com/comit/data/extension/MultiPart.kt
  data/src/main/java/com/comit/data/repository/FileRepositoryImpl.kt
  di/src/main/java/com/comit/di/RemoteDataSourceModule.kt
  di/src/main/java/com/comit/di/RepositoryModule.kt
  domain/src/main/java/com/comit/domain/repository/FileRepository.kt
  domain/src/main/java/com/comit/domain/usecase/files/UploadFileListUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/files/UploadFileUseCase.kt
  remote/src/main/java/com/comit/remote/api/FilesAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteFileDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/response/files/FileListResponse.kt
Labels: 기능 추가

#26 SImTong Calendar
  core-design-system/src/main/java/com/comit/core_design_system/color/SimTongColor.kt
  core-design-system/src/main/java/com/comit/core_design_system/component/FoodList.kt
  core-design-system/src/main/java/com/comit/core_design_system/icon/SimTongIcon.kt
  core-design-system/src/main/java/com/comit/core_design_system/modifier/clickable.kt
  core-design-system/src/main/java/com/comit/core_design_system/theme/theme.kt
  core-design-system/src/main/java/com/comit/core_design_system/typography/typography.kt
  core-design-system/src/main/res/drawable/ic_calendar_after.xml
  core-design-system/src/main/res/drawable/ic_calendar_before.xml
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/SimTongCalendar.kt
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/SimTongCalendarGetList.kt
  feature/feature-home/src/main/java/com/comit/feature_home/navigation/HomeNavigation.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/WriteClosedDayScreen.kt
  feature/feature-home/src/main/res/values/string.xml
  navigator/src/main/java/com/comit/navigator/SimTongScreen.kt
Labels: 기능 추가

#34 Merge: SIMT-47 Holidays API
  data/src/main/java/com/comit/data/datasource/RemoteHolidayDataSource.kt
  data/src/main/java/com/comit/data/repository/HolidayRepositoryImpl.kt
  di/src/main/java/com/comit/di/RemoteDataSourceModule.kt
  di/src/main/java/com/comit/di/RepositoryModule.kt
  domain/src/main/java/com/comit/domain/repository/HolidayRepository.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/DayOffHolidaysUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/FetchHolidaysUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/SetAnnualUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/SetWorkUseCase.kt
  model/src/main/java/com/comit/model/HolidayList.kt
  remote/src/main/java/com/comit/remote/api/HolidayAPI.kt
  remote/src/main/java/com/comit/remote/api/MenuAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteHolidayDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteMenuDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/mapper/ResponseToModel.kt
  remote/src/main/java/com/comit/remote/response/holidays/FetchHolidaysResponse.kt
  remote/src/main/java/com/comit/remote/response/holidays/SimpleHolidaysResponse.kt
Labels: 기능 추가

#35 Merge: SIMT-48 Authoirzation Interceptor
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  data/src/main/java/com/comit/data/datasource/LocalAuthDataSource.kt
  data/src/main/java/com/comit/data/datasource/RemoteCommonsDataSource.kt
  data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/comit/data/repository/CommonsRepositoryImpl.kt
  di/src/main/java/com/comit/di/LocalDataSourceModule.kt
  di/src/main/java/com/comit/di/PreferenceModule.kt
  di/src/main/java/com/comit/di/ProvideContext.kt
  domain/src/main/java/com/comit/domain/repository/CommonsRepository.kt
  local/build.gradle.kts
  local/src/main/java/com/comit/local/datasource/LocalAuthDataSourceImpl.kt
  local/src/main/java/com/comit/local/extension/datastore.kt
  local/src/main/java/com/comit/local/extension/time.kt
  local/src/main/java/com/comit/local/preference/AuthPreference.kt
  local/src/main/java/com/comit/local/preference/AuthPreferenceImpl.kt
  local/src/main/java/com/comit/local/preference/ProvideDataStore.kt
  remote/src/main/java/com/comit/remote/api/CommonsAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteCommonsDataSourceImpl.kt
Labels: 기능 추가, Chore

#37 Merge: SIMT-56 FindEmployeeNumber Refactor & Connect
  common/src/main/java/com/comit/common/compose/ToastWrapper.kt
  common/src/main/java/com/comit/common/domain/unit/Time.kt
  core-design-system/src/main/java/com/comit/core_design_system/typography/typography.kt
  data/src/main/java/com/comit/data/datasource/LocalAuthDataSource.kt
  data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/comit/data/repository/AuthRepositoryImpl.kt
  di/src/main/java/com/comit/di/ProvideContext.kt
  di/src/main/java/com/comit/di/RemoteDataSourceModule.kt
  di/src/main/java/com/comit/di/RetrofitModule.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/mvi/FindEmployeeNumContract.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/mvi/FindPasswordContract.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/navigation/AuthNavigation.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/AuthFindScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/employeeNumber/FindEmployeeNumScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/employeeNumber/SpotUiModel.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/findEmployeeNumber/FindEmployeeNumScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordCheckUserScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordEmailCodeScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordFixPasswordScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/vm/FindEmployeeNumViewModel.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/vm/FindPasswordViewModel.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/vm/SignInViewModel.kt
  local/build.gradle.kts
  local/src/main/java/com/comit/local/datasource/LocalAuthDataSourceImpl.kt
  model/src/main/java/com/comit/model/Token.kt
  remote/build.gradle.kts
  remote/src/main/java/com/comit/remote/mapper/ResponseToModel.kt
Labels: 기능 추가

#39 Merge: SIMT-61 비밀번호 찾기 Refactor & Connect
  common-compose/src/main/java/com/comit/common/layout.kt
  common-compose/src/main/java/com/comit/common/timer.kt
  core-design-system/src/main/java/com/comit/core_design_system/util/time.kt
  data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/comit/data/util/SimTongApiCall.kt
  domain/src/main/java/com/comit/domain/exception/HttpException.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/mvi/FindPasswordContract.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/AuthFindScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordEmailCodeScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordFixPasswordScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpNameScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpNicknameScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpPasswordScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/SignUpVerifyScreen.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/vm/FindPasswordViewModel.kt
  feature/feature-auth/src/main/res/values/string.xml
  remote/src/main/java/com/comit/remote/api/EmailAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteEmailDataSourceImpl.kt
Labels: 기능 추가, 리펙토링

#40 Merge: SIMT-60 fix token interceptor
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  data/src/main/java/com/comit/data/extension/MultiPart.kt
  data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/comit/data/interceptor/ReissueTokenResponse.kt
Labels: 버그

#44 Merge: SIMT-67 Fix Bitmap Parsing
  common-compose/build.gradle.kts
  common-compose/src/main/java/com/comit/common/SimImageUploadLayout.kt
  common-util/src/main/java/com/comit/common/convert/FileUtil.kt
  common-util/src/main/java/com/comit/common/convert/UriUtil.kt
  core-design-system/src/main/java/com/comit/core_design_system/modifier/clickable.kt
  data/src/main/java/com/comit/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/comit/data/util/FormDataUtil.kt
  feature/feature-auth/src/main/java/com/comit/feature_auth/screen/signUp/4_SignUpNicknameScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
Labels: 버그

#45 Merge: SIMT-69 Onboarding Finished
  app/build.gradle.kts
  feature/feature-onboarding/.gitignore
  feature/feature-onboarding/build.gradle.kts
  feature/feature-onboarding/consumer-rules.pro
  feature/feature-onboarding/proguard-rules.pro
  feature/feature-onboarding/src/androidTest/java/com/comit/feature_auth/ExampleInstrumentedTest.kt
  feature/feature-onboarding/src/main/AndroidManifest.xml
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/.gitkeep
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/mvi/FindEmployeeNumContract.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/mvi/FindPasswordContract.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/mvi/SIgnUpContract.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/mvi/SignInContract.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/navigation/AuthNavigation.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/AuthFindScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/employeeNumber/FindEmployeeNumScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/employeeNumber/SpotUiModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordCheckUserScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordEmailCodeScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordFixPasswordScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/1_SignUpNameScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/2_SignUpVerifyScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/3_SignUpPasswordScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/4_SignUpNicknameScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/SignUpScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/SignUpStep.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/splash/StartScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/utils/BottomSheetType.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/utils/changeBottomSheetState.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/FindEmployeeNumViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/FindPasswordViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignInViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignUpViewModel.kt
  feature/feature-onboarding/src/main/res/drawable/bg_splash_page1.png
  feature/feature-onboarding/src/main/res/drawable/bg_splash_page2.png
  feature/feature-onboarding/src/main/res/drawable/bg_splash_page3.png
  feature/feature-onboarding/src/main/res/drawable/bg_splash_page4.png
  feature/feature-onboarding/src/main/res/drawable/bg_splash_page5.png
  feature/feature-onboarding/src/main/res/drawable/bg_splash_page6.png
  feature/feature-onboarding/src/main/res/drawable/bg_splash_simtong.png
  feature/feature-onboarding/src/main/res/drawable/bg_splash_title.png
  feature/feature-onboarding/src/main/res/drawable/ic_dang.xml
  feature/feature-onboarding/src/main/res/drawable/ic_sim.xml
  feature/feature-onboarding/src/main/res/drawable/ic_splash_logo.xml
  feature/feature-onboarding/src/main/res/values/string.xml
  feature/feature-onboarding/src/test/java/com/comit/feature_auth/ExampleUnitTest.kt
  navigator/src/main/java/com/comit/navigator/SimTongScreen.kt
  settings.gradle.kts
Labels: 기능 추가, 리펙토링

#46 Merge: SIMT-71 Salary WebView connect
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  feature/feature-home/build.gradle.kts
  feature/feature-home/src/main/AndroidManifest.xml
  feature/feature-home/src/main/java/com/comit/feature_home/navigation/HomeNavigation.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/SalaryWebViewScreen.kt
  navigator/src/main/java/com/comit/navigator/SimTongScreen.kt
Labels: 기능 추가

#47 Merge: SIMT-65 MyPage Image Upload
  common-compose/src/main/java/com/comit/common/SimImageUploadLayout.kt
  data/src/main/java/com/comit/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/comit/data/util/SimTongApiCall.kt
  domain/src/main/java/com/comit/domain/repository/AuthRepository.kt
  domain/src/main/java/com/comit/domain/usecase/users/ChangeProfileImageUseCase.kt
  feature/feature-mypage/build.gradle.kts
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/mvi/MyPageContract.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/navigation/MyPageNavigation.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/email/FixEmailScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/password/FixPassword.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/workplace/FixWorkPlaceScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/splash/StartScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignInViewModel.kt
  remote/src/main/java/com/comit/remote/api/AuthAPI.kt
  remote/src/main/java/com/comit/remote/api/CommonsAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteAuthDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteCommonsDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/request/commons/ChangePasswordRequest.kt
Labels: 기능 추가

#48 Merge: SIMT-64 달력 관련 기능들
  core-design-system/src/main/java/com/comit/core_design_system/icon/SimTongIcon.kt
  core-design-system/src/main/res/drawable/ic_option_horizontal_bold.xml
  core-design-system/src/main/res/drawable/ic_schedule_off.xml
  core-design-system/src/main/res/drawable/ic_schedule_on.xml
  data/src/main/java/com/comit/data/datasource/RemoteHolidayDataSource.kt
  data/src/main/java/com/comit/data/datasource/RemoteScheduleDataSource.kt
  data/src/main/java/com/comit/data/repository/HolidayRepositoryImpl.kt
  data/src/main/java/com/comit/data/repository/ScheduleRepositoryImpl.kt
  domain/src/main/java/com/comit/domain/repository/HolidayRepository.kt
  domain/src/main/java/com/comit/domain/repository/ScheduleRepository.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/DayOffHolidaysUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/AddPersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/ChangePersonalScheduleUseCase.kt
  feature/feature-home/build.gradle.kts
  feature/feature-home/src/main/java/com/comit/feature_home/Util.kt
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/GetHolidayViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/GetWorkCountViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/SimTongCalendar.kt
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/SimTongCalendarGetList.kt
  feature/feature-home/src/main/java/com/comit/feature_home/mvi/CloseDayContract.kt
  feature/feature-home/src/main/java/com/comit/feature_home/mvi/FetchHolidayContract.kt
  feature/feature-home/src/main/java/com/comit/feature_home/mvi/FetchScheduleContract.kt
  feature/feature-home/src/main/java/com/comit/feature_home/mvi/WriteScheduleContract.kt
  feature/feature-home/src/main/java/com/comit/feature_home/navigation/HomeNavigation.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/SalaryWebViewScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/closeday/CloseDayViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/closeday/WriteClosedDayScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/WriteScheduleScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/WriteScheduleViewModel.kt
  feature/feature-home/src/main/res/values/string.xml
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/navigation/MyPageNavigation.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/splash/StartScreen.kt
  navigator/src/main/java/com/comit/navigator/SimTongScreen.kt
  remote/src/main/java/com/comit/remote/api/HolidayAPI.kt
  remote/src/main/java/com/comit/remote/api/ScheduleAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteHolidayDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteScheduleDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/request/holidays/DayOffRequest.kt
  remote/src/main/java/com/comit/remote/request/schedules/AddPersonalScheduleRequest.kt
  remote/src/main/java/com/comit/remote/request/schedules/ChangePersonalScheduleRequest.kt
  remote/src/main/java/com/comit/remote/response/holidays/FetchHolidaysResponse.kt
Labels: 기능 추가

#50 Merge: SIMT-68 meal refactor & connect
  core-design-system/src/main/java/com/comit/core_design_system/component/FoodList.kt
  core-design-system/src/main/java/com/comit/core_design_system/component/MealList.kt
  core-design-system/src/main/res/drawable/img_food.png
  core-design-system/src/main/res/drawable/img_food_red.png
  core-design-system/src/main/res/drawable/img_meal_red.png
  core-design-system/src/main/res/drawable/img_meal_white.png
  data/src/main/java/com/comit/data/datasource/RemoteMenuDataSource.kt
  data/src/main/java/com/comit/data/repository/MenuRepositoryImpl.kt
  domain/src/main/java/com/comit/domain/model/MealEntity.kt
  domain/src/main/java/com/comit/domain/repository/MenuRepository.kt
  domain/src/main/java/com/comit/domain/usecase/menu/FetchMenuUseCase.kt
  feature/feature-home/src/main/java/com/comit/feature_home/contract/HomeContract.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/HomeViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignInViewModel.kt
  model/src/main/java/com/comit/model/MenuList.kt
  remote/src/main/java/com/comit/remote/api/MenuAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteMenuDataSourceImpl.kt
Labels: 기능 추가, 리펙토링

#51 Merge: SIMT-75 키패드 변경
  core-design-system/src/main/java/com/comit/core_design_system/component/MealList.kt
  domain/src/main/java/com/comit/domain/usecase/menu/FetchMenuUseCase.kt
  feature/feature-home/src/main/java/com/comit/feature_home/contract/HomeContract.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/WriteScheduleScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/HomeViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/email/FixEmailScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/password/FixPassword.kt
  feature/feature-mypage/src/main/res/values/string.xml
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
  model/src/main/java/com/comit/model/MenuList.kt
Labels: 리펙토링

#52 Merge: SIMT-76 앱 디테일 잡기
  app/release/output-metadata.json
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/values/strings.xml
  common-util/src/main/java/com/comit/common/convert/FileUtil.kt
  common-util/src/main/java/com/comit/common/format/email.kt
  common-util/src/main/java/com/comit/common/unit/file.kt
  fastlane/report.xml
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/mvi/MyPageContract.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/mvi/FindEmployeeNumContract.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/mvi/FindPasswordContract.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/mvi/SIgnUpContract.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/mvi/SignInContract.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/AuthFindScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/employeeNumber/FindEmployeeNumMainScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordCheckUserScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordEmailCodeScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordFixPasswordScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/1_SignUpNameScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/2_SignUpVerifyScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/4_SignUpNicknameScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/SignUpScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/FindEmployeeNumViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/FindPasswordViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignUpViewModel.kt
  remote/src/main/java/com/comit/remote/api/CommonsAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteCommonsDataSourceImpl.kt
Labels: 기능 추가, 리펙토링, Chore

#54 Merge: SIMT-78 일정 확인 페이지 ui수정
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/workplace/FixWorkPlaceScreen.kt
Labels: 리펙토링

#56 Merge: SIMT-80 GlobalException Handling
  app/release/output-metadata.json
  app/src/main/java/com/comit/simtong/handler/SimTongExceptionHandler.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/HomeViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/navigation/AuthNavigation.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/error/ErrorScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/utils/AuthDeepLinkKeyUtil.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/FindEmployeeNumViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/FindPasswordViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignInViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignUpViewModel.kt
  feature/feature-onboarding/src/main/res/values/string.xml
  navigator/src/main/java/com/comit/navigator/SimTongScreen.kt
Labels: 기능 추가

#55 Merge: SIMT-79 마이페이지 서버연동 기능들들 수정
  common-util/src/main/java/com/comit/common/format/nickname.kt
  common-util/src/main/java/com/comit/common/format/password.kt
  data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/comit/data/interceptor/EmptyBodyInterceptor.kt
  data/src/main/java/com/comit/data/repository/AuthRepositoryImpl.kt
  di/src/main/java/com/comit/di/RetrofitModule.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/mvi/EmailContract.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/mvi/InputCertificationContract.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/mvi/NickNameContract.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/mvi/PasswordContract.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/mvi/WorkPlaceContract.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/navigation/MyPageNavigation.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/email/FixEmailScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/email/FixEmailViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/email/InputCertification.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/email/InputCertificationViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/nickname/FixNickNameScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/nickname/FixNickNameViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/password/FixPassword.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/password/FixPasswordViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/workplace/FixWorkPlaceScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/workplace/FixWorkPlaceViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/utils/MyPageDeepLinkKeyUtil.kt
  feature/feature-mypage/src/main/res/values/string.xml
  remote/src/main/java/com/comit/remote/api/AuthAPI.kt
  remote/src/main/java/com/comit/remote/api/CommonsAPI.kt
  remote/src/main/java/com/comit/remote/api/HolidayAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteAuthDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteCommonsDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteHolidayDataSourceImpl.kt
Labels: 리펙토링

#57 Merge: SIMT-81 Network Connect
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comit/simtong/handler/NetworkConnection.kt
  app/src/main/java/com/comit/simtong/handler/SimTongExceptionHandler.kt
  app/src/main/java/com/comit/simtong/root/MainActivity.kt
  domain/src/main/java/com/comit/domain/usecase/commons/ChangePasswordUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/commons/CheckOldPasswordUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/commons/FetchSpotsUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/commons/FindAccountExistUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/commons/FindEmailDuplicationUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/commons/FindEmployeeNumberUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/commons/InitializationPasswordUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/email/CheckEmailCodeUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/email/SendEmailCodeUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/files/UploadFileListUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/files/UploadFileUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/DayOffHolidaysUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/FetchHolidaysUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/SetAnnualUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/SetWorkUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/menu/FetchMenuUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/menu/FetchPublicMenuUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/AddPersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/ChangePersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/DeletePersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/FetchPersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/ChangeEmailUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/ChangeNicknameUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/ChangeProfileImageUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/ChangeSpotUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/CheckNicknameDuplicationUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/FetchUserInformationUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/SignInUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/SignUpUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/VerificationEmployeeUseCase.kt
Labels: 기능 추가

#58 Merge: SIMT-81 Auth UX 개선
  app/src/main/AndroidManifest.xml
  common-util/src/main/java/com/comit/common/format/RegexUtils.kt
  common-util/src/main/java/com/comit/common/format/nickname.kt
  common-util/src/main/java/com/comit/common/format/password.kt
  core-design-system/src/main/java/com/comit/core_design_system/component/TextField.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/email/FixEmailScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/email/InputCertification.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/nickname/FixNickNameScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/employeeNumber/FindEmployeeNumMainScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordCheckUserScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/password/FindPasswordFixPasswordScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/1_SignUpNameScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/3_SignUpPasswordScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/4_SignUpNicknameScreen.kt
  feature/feature-onboarding/src/main/res/values/string.xml
Labels: 리펙토링

#59 Merge: SIMT-85 일정 수정 페이지 버그수정
  app/src/main/java/com/comit/simtong/root/MainActivity.kt
  feature/feature-home/src/main/java/com/comit/feature_home/mvi/CloseDayContract.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/closeday/CloseDayViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/closeday/WriteClosedDayScreen.kt
Labels: 버그

#61 Merge: SIMT-87 NetworkConnectionInterceptor
  app/src/main/java/com/comit/simtong/handler/NetworkConnection.kt
  app/src/main/java/com/comit/simtong/handler/SimTongExceptionHandler.kt
  app/src/main/java/com/comit/simtong/root/MainActivity.kt
  common-util/src/main/java/com/comit/common/extension/toast.kt
  data/src/main/AndroidManifest.xml
  data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/comit/data/util/SimTongApiCall.kt
  di/src/main/java/com/comit/di/NetworkModule.kt
  domain/src/main/java/com/comit/domain/exception/HttpException.kt
  domain/src/main/java/com/comit/domain/exception/NetworkException.kt
  domain/src/main/java/com/comit/domain/exception/ThrowUnknownException.kt
  domain/src/main/java/com/comit/domain/usecase/commons/ChangePasswordUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/commons/CheckOldPasswordUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/commons/FetchSpotsUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/commons/FindAccountExistUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/commons/FindEmailDuplicationUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/commons/FindEmployeeNumberUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/commons/InitializationPasswordUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/email/CheckEmailCodeUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/email/SendEmailCodeUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/files/UploadFileListUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/files/UploadFileUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/DayOffHolidaysUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/FetchHolidaysUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/SetAnnualUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/SetWorkUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/menu/FetchMenuUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/menu/FetchPublicMenuUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/AddPersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/ChangePersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/DeletePersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/FetchPersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/ChangeEmailUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/ChangeNicknameUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/ChangeProfileImageUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/ChangeSpotUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/CheckNicknameDuplicationUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/FetchUserInformationUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/SignInUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/SignUpUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/VerificationEmployeeUseCase.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/closeday/CloseDayViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/WriteScheduleViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/HomeViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/email/FixEmailViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/email/InputCertificationViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/nickname/FixNickNameViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/password/FixPasswordViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/workplace/FixWorkPlaceViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/FindEmployeeNumViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/FindPasswordViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignInViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignUpViewModel.kt
  feature/feature-onboarding/src/main/res/values/string.xml
Labels: 기능 추가, 리펙토링

#62 Merge: SIMT-89 disbled doubleClicked
  core-design-system/src/main/java/com/comit/core_design_system/component/CarrotMarket.kt
  core-design-system/src/main/java/com/comit/core_design_system/component/Comment.kt
  core-design-system/src/main/java/com/comit/core_design_system/component/IdeaComponent.kt
  core-design-system/src/main/java/com/comit/core_design_system/component/NoticeBoardItem.kt
  core-design-system/src/main/java/com/comit/core_design_system/modifier/clickable.kt
  core-design-system/src/main/java/com/comit/core_design_system/modifier/cutter.kt
  core-design-system/src/main/java/com/comit/core_design_system/typography/typography.kt
  data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
  di/src/main/java/com/comit/di/NetworkModule.kt
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/SimTongCalendar.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/closeday/WriteClosedDayScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
Labels: 버그, 기능 추가

#63 Merge: SIMT-88 change schedule api
  app/build.gradle.kts
  build.gradle.kts
  common-compose/src/main/java/com/comit/common/utils/Util.kt
  data/src/main/java/com/comit/data/datasource/RemoteHolidayDataSource.kt
  data/src/main/java/com/comit/data/datasource/RemoteMenuDataSource.kt
  data/src/main/java/com/comit/data/datasource/RemoteScheduleDataSource.kt
  data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/comit/data/repository/HolidayRepositoryImpl.kt
  data/src/main/java/com/comit/data/repository/MenuRepositoryImpl.kt
  data/src/main/java/com/comit/data/repository/ScheduleRepositoryImpl.kt
  domain/src/main/java/com/comit/domain/repository/HolidayRepository.kt
  domain/src/main/java/com/comit/domain/repository/MenuRepository.kt
  domain/src/main/java/com/comit/domain/repository/ScheduleRepository.kt
  domain/src/main/java/com/comit/domain/usecase/holiday/FetchHolidaysUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/menu/FetchMenuUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/FetchPersonalScheduleUseCase.kt
  feature/feature-home/src/main/java/com/comit/feature_home/Util.kt
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/GetHolidayViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/GetWorkCountViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/SimTongCalendar.kt
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/SimTongCalendarGetList.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/closeday/WriteClosedDayScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/HomeViewModel.kt
  gradle/wrapper/gradle-wrapper.properties
  remote/src/main/java/com/comit/remote/api/HolidayAPI.kt
  remote/src/main/java/com/comit/remote/api/MenuAPI.kt
  remote/src/main/java/com/comit/remote/api/ScheduleAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteHolidayDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteMenuDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteScheduleDataSourceImpl.kt
Labels: 리펙토링

#64 Merge: SIMT-93 UI Detail
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comit/simtong/root/MainActivity.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  common-compose/src/main/java/com/comit/common/layout.kt
  common-compose/src/main/java/com/comit/common/padding.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleScreen.kt
  feature/feature-home/src/main/res/drawable/ic_home_coin.xml
  feature/feature-home/src/main/res/drawable/ic_home_holiday.xml
  feature/feature-home/src/main/res/drawable/ic_home_schedule.xml
  feature/feature-home/src/main/res/values/string.xml
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/mvi/SignInContract.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/1_SignUpNameScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/2_SignUpVerifyScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/3_SignUpPasswordScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/SignUpScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignInViewModel.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/SignUpViewModel.kt
Labels: 버그

#65 Merge: SIMT-95 자동 로그인 구현
  data/src/main/java/com/comit/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/comit/data/repository/CommonsRepositoryImpl.kt
  domain/src/main/java/com/comit/domain/repository/CommonsRepository.kt
  domain/src/main/java/com/comit/domain/usecase/commons/TokenReissueUseCase.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/mvi/StartContract.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/splash/StartScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/StartViewModel.kt
  remote/src/main/java/com/comit/remote/api/CommonsAPI.kt
Labels: 기능 추가

#66 Merge: SIMT-94 fix bug
  core-design-system/src/main/java/com/comit/core_design_system/component/Header.kt
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/SimTongCalendar.kt
  feature/feature-home/src/main/java/com/comit/feature_home/navigation/HomeNavigation.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/alarm/AlarmScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageViewModel.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/fix/workplace/FixWorkPlaceViewModel.kt
  navigator/src/main/java/com/comit/navigator/SimTongScreen.kt
Labels: 버그, 리펙토링

#67 Merge: SIMT-82, SIMT-81 Firebase Crashlytics & Analytics
  app/build.gradle.kts
  app/proguard-rules.pro
  build.gradle.kts
  buildSrc/src/main/java/BuildPlugins.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  domain/build.gradle.kts
  domain/src/main/java/com/comit/domain/exception/ThrowUnknownException.kt
Labels: 기능 추가

#69 Merge: SIMT-98 fix clickable
  core-design-system/src/main/java/com/comit/core_design_system/modifier/clickable.kt
  core-design-system/src/main/java/com/comit/core_design_system/typography/typography.kt
Labels: 버그

#68 Merge: SIMT-77 timer dialog 추가
  common-compose/src/main/java/com/comit/common/BtnField.kt
  common-compose/src/main/java/com/comit/common/dialog/SimTongCalendarDialog.kt
  common-compose/src/main/java/com/comit/common/dialog/timerdialog/ListItemPicker.kt
  common-compose/src/main/java/com/comit/common/dialog/timerdialog/NumberPicker.kt
  common-compose/src/main/java/com/comit/common/dialog/timerdialog/SimTongTimerDialog.kt
  common-compose/src/main/java/com/comit/common/utils/Util.kt
  common-compose/src/main/res/values/string.xml
  data/src/main/java/com/comit/data/datasource/RemoteScheduleDataSource.kt
  data/src/main/java/com/comit/data/repository/ScheduleRepositoryImpl.kt
  domain/src/main/java/com/comit/domain/repository/ScheduleRepository.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/AddPersonalScheduleUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/schedule/ChangePersonalScheduleUseCase.kt
  feature/feature-home/src/main/java/com/comit/feature_home/mvi/WriteScheduleContract.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/WriteScheduleScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/WriteScheduleViewModel.kt
  feature/feature-home/src/main/res/values/string.xml
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/mvi/FindEmployeeNumContract.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/find/employeeNumber/FindEmployeeNumMainScreen.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteScheduleDataSourceImpl.kt
Labels: 기능 추가

#71 Merge: SIMT-101 자동로그인 fix
  app/src/main/java/com/comit/simtong/handler/SimTongExceptionHandler.kt
  data/src/main/java/com/comit/data/repository/CommonsRepositoryImpl.kt
  domain/src/main/java/com/comit/domain/exception/NeedLoginException.kt
  domain/src/main/java/com/comit/domain/exception/ThrowUnknownException.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/mvi/StartContract.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/splash/StartScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/vm/StartViewModel.kt
Labels: 버그

#73 Merge: SIMT-102 개인정보처리방침 추가
  buildSrc/src/main/java/Versions.kt
  feature/feature-mypage/build.gradle.kts
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/navigation/MyPageNavigation.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/PrivacyPolicyScreen.kt
  feature/feature-mypage/src/main/res/values/string.xml
  navigator/src/main/java/com/comit/navigator/SimTongScreen.kt
Labels: 기능 추가

#74 Publish v1.0.1
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  feature/feature-mypage/build.gradle.kts
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/navigation/MyPageNavigation.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/PrivacyPolicyScreen.kt
  feature/feature-mypage/src/main/res/values/string.xml
  navigator/src/main/java/com/comit/navigator/SimTongScreen.kt
Labels: Publish

#76 Merge: SIMT-92 홈화면 예외처리
  feature/feature-home/src/main/java/com/comit/feature_home/mvi/CloseDayContract.kt
  feature/feature-home/src/main/java/com/comit/feature_home/mvi/FetchScheduleContract.kt
  feature/feature-home/src/main/java/com/comit/feature_home/navigation/HomeNavigation.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/WriteClosedDayScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/CloseDayViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/GetHolidayViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/GetWorkCountViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/ShowScheduleViewModel.kt
Labels: 기능 추가

#75 refactor: SIMT-104 메인 페이지, 일정 작성 달력 크기 수정
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/SimTongCalendar.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleScreen.kt
Labels: 리펙토링

#77 Publish v1.0.2
  domain/src/main/java/com/comit/domain/exception/ThrowUnknownException.kt
  feature/feature-home/src/main/java/com/comit/feature_home/calendar/SimTongCalendar.kt
  feature/feature-home/src/main/java/com/comit/feature_home/mvi/CloseDayContract.kt
  feature/feature-home/src/main/java/com/comit/feature_home/mvi/FetchScheduleContract.kt
  feature/feature-home/src/main/java/com/comit/feature_home/navigation/HomeNavigation.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/WriteClosedDayScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/ShowScheduleScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/CloseDayViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/GetHolidayViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/GetWorkCountViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/vm/ShowScheduleViewModel.kt
Labels: 버그

#78 Merge: SIMT-106 enabled Webview JS
  feature/feature-home/src/main/java/com/comit/feature_home/screen/SalaryWebViewScreen.kt
Labels: 버그
