Repository Team-ComIT/SimTong-Android, pull requests merged in 2023-01, with the labels that each got.

#80 Merge: SIMT-111 FetchAndSave DeviceToken
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comit/simtong/firebase/FCMManager.kt
  app/src/main/java/com/comit/simtong/firebase/firebase.kt
  app/src/main/java/com/comit/simtong/root/MainActivity.kt
  app/src/main/java/com/comit/simtong/root/MainViewModel.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/src/main/java/com/comit/data/datasource/LocalAuthDataSource.kt
  data/src/main/java/com/comit/data/datasource/RemoteAuthDataSource.kt
  data/src/main/java/com/comit/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/comit/domain/repository/AuthRepository.kt
  domain/src/main/java/com/comit/domain/usecase/users/SaveDeviceTokenUseCase.kt
  feature/feature-onboarding/src/main/AndroidManifest.xml
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/SignUpScreen.kt
  local/src/main/java/com/comit/local/datasource/LocalAuthDataSourceImpl.kt
  local/src/main/java/com/comit/local/preference/AuthPreference.kt
  local/src/main/java/com/comit/local/preference/AuthPreferenceImpl.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteAuthDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/request/users/SignInRequest.kt
  remote/src/main/java/com/comit/remote/request/users/SignUpRequest.kt
Labels: 기능 추가

#83 Merge: 달력, 일정 추가 페이지 ui 사이즈 및 규격 수정
  feature/feature-home/src/main/java/com/comit/feature_home/screen/WriteClosedDayScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/WriteScheduleScreen.kt
Labels: 리펙토링

#82 Merge: SIMT-115 나위 급여 정보, 휴무표 작성 버튼 리플 효과 범위 수정
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
Labels: 리펙토링

#81 연차, 근무 신청 405에러 수정
  app/src/main/java/com/comit/simtong/root/MainViewModel.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/WriteClosedDayScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
  remote/src/main/java/com/comit/remote/api/HolidayAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteHolidayDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/request/holidays/SetAnnualRequest.kt
  remote/src/main/java/com/comit/remote/request/holidays/SetWorkRequest.kt
Labels: 버그

#86 Publish 1.0.4
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/comit/simtong/firebase/FCMManager.kt
  app/src/main/java/com/comit/simtong/firebase/firebase.kt
  app/src/main/java/com/comit/simtong/root/MainActivity.kt
  app/src/main/java/com/comit/simtong/root/MainViewModel.kt
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  core-design-system/src/main/java/com/comit/core_design_system/icon/SimTongIcon.kt
  core-design-system/src/main/res/drawable/ic_logo.png
  core-design-system/src/main/res/drawable/ic_logo.xml
  data/src/main/java/com/comit/data/datasource/LocalAuthDataSource.kt
  data/src/main/java/com/comit/data/datasource/RemoteAuthDataSource.kt
  data/src/main/java/com/comit/data/repository/AuthRepositoryImpl.kt
  detekt-config.yml
  domain/src/main/java/com/comit/domain/repository/AuthRepository.kt
  domain/src/main/java/com/comit/domain/usecase/users/ClearTokenUseCase.kt
  domain/src/main/java/com/comit/domain/usecase/users/SaveDeviceTokenUseCase.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/HomeScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/WriteClosedDayScreen.kt
  feature/feature-home/src/main/java/com/comit/feature_home/screen/schedule/WriteScheduleScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/screen/MyPageScreen.kt
  feature/feature-mypage/src/main/java/com/comit/feature_mypage/vm/MyPageViewModel.kt
  feature/feature-onboarding/src/main/AndroidManifest.xml
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signIn/SignInScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/signUp/SignUpScreen.kt
  feature/feature-onboarding/src/main/java/com/comit/feature_auth/screen/splash/StartScreen.kt
  feature/feature-onboarding/src/main/res/drawable/ic_chinese_simtong.png
  feature/feature-onboarding/src/main/res/drawable/ic_sign_in_logo.xml
  feature/feature-onboarding/src/main/res/drawable/ic_sign_in_title.png
  local/src/main/java/com/comit/local/datasource/LocalAuthDataSourceImpl.kt
  local/src/main/java/com/comit/local/preference/AuthPreference.kt
  local/src/main/java/com/comit/local/preference/AuthPreferenceImpl.kt
  remote/src/main/java/com/comit/remote/api/HolidayAPI.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteAuthDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/datasource/RemoteHolidayDataSourceImpl.kt
  remote/src/main/java/com/comit/remote/request/holidays/SetAnnualRequest.kt
  remote/src/main/java/com/comit/remote/request/holidays/SetWorkRequest.kt
  remote/src/main/java/com/comit/remote/request/users/SignInRequest.kt
  remote/src/main/java/com/comit/remote/request/users/SignUpRequest.kt
Labels: Publish
